# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webjeda
email: hello@webjeda.com
description: > # this means to ignore newlines until "baseurl:"
 WebJeda is a company oriented towards building modern websites and apps. It also provides smart hosting solutions. Contact us for modern, fast and responsive websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://webjeda.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

sass:
 style: compressed
 
 
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
review: 
  link: http://search.google.com/local/writereview?placeid=ChIJx113w8QUuzsR_3IiWBPrucE
  short-link: https://goo.gl/fAcxe9
  
response:
    form: https://docs.google.com/forms/d/e/1FAIpQLSfmSZif4GDstMLnMKc35fVDJ9SoHDkmMUhr-_0fvVZBH4TKyw/viewform?usp=sf_link#responses
    spreadsheet: https://docs.google.com/spreadsheets/d/1hro6nLvSeY_9Xb8QMicFDz2Ju9q38xcB2FhF8XjMl3s/edit#gid=877421763

gems: 
    - jekyll-seo-tag