title: Webjeda
description: WebJeda is a web designing company based in Bengaluru. Designing beautiful, responsive and functional websites is our passion.
url: http://webjeda.com
logo: /images/apple-touch-icon-ipad-retina-152x152.png

contact: '/contact.html#wj-contact'
learn-more: '/about.html#wj-features'


github: https://github.com/sharu725
youtube: https://www.youtube.com/webjeda

twitter:
  username: webjeda


social:
  name: Webjeda
  links:
    - https://twitter.com/webjeda
    - https://facebook.com/webjeda
    - https://plus.google.com/+WebJeda
    - https://github.com/sharu725


facebook:
 app_id: 549480635219583
 publisher: webjeda
 admins: sharu725

include: ["_pages"]
exclude:
    - _extra


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
review: 
  link: http://search.google.com/local/writereview?placeid=ChIJx113w8QUuzsR_3IiWBPrucE
  short-link: https://goo.gl/fAcxe9




plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    